In [180]:
x=[ ele for elem in input().split(sep=" ", maxsplit=count)  ]

1 2 3 4 5 6


In [181]:
x

[6, 6, 6, 6, 6]

In [182]:

# input size of the list
n = int(input("Enter the size of list : "))
# store integers in a list using map, split and strip functions
lst = list(map(int, input(
    "Enter the integer elements of list(Space-Separated): ").strip().split()))[:n]
print('The list is:', lst)   # printing the list

Enter the size of list : 2
Enter the integer elements of list(Space-Separated): 1 3 4 5 6 7 8
The list is: [1, 3]


In [184]:
inputs = [input() for i in range(6 - 1)]

1 2 3 4 5 6 7
3
5
9
8


In [185]:
inputs


['1 2 3 4 5 6 7', '3', '5', '9', '8']

#### 










In [2]:
import sys
sys.stdout.write('gfg')

gfg

3

In [3]:
import sys
  
# stdout assigned to a variable
var = sys.stdout
arr = ['geeks', 'for', 'geeks']
  
# printing everything in the same line
for i in arr:
    var.write(i)
  
# printing everything in a new line
for j in arr:
    var.write('\n'+j)

geeksforgeeks
geeks
for
geeks

In [9]:
n=int(input())
s=[]
for i in range(n):
    s.append(input())
set1=set(s)
print(set1)

4
lkjslhf
abc
jhsjh
abc
{'lkjslhf', 'abc', 'jhsjh'}


In [14]:
## taking input with limit in set and list
data = [i for i in input().strip().split()[0:5]]
## Or
s=set(input().split(" ")[0:5])
s=input().split(" ")[0:5]

jd  sljhh sjfhh hlf sjlhfljh fljsh  slfh


In [64]:
sum(s)

28

In [34]:
N=int(input())

5


In [35]:
i=0


while i<=N:
    l1=input().split(" ")[0:2]
    if l1[0].lower()=="pop":
        s.pop()
    elif l1[0].lower()=="remove":
       s.remove(int(l1[1])) 
    elif l1[0].lower()=="discard":
        s.discard(int(l1[1]))

    i=i+1
print(sum(s))

In [45]:
s.pop()    # pop removes first element

3

In [46]:
s

{5, 7}

In [48]:
s.discard(5)

In [49]:
s

{7}

In [51]:
s.remove(7)

In [52]:
s

set()

In [57]:
l1=(input().split(" ")[0:2])
    #if l1[0]=="remove" or 
l1[0].lower()

Remove


'remove'

In [65]:
n=int(input())
s=[]
s=map(int, input().split(" ")[0:5])
s=set(s)
N=int(input())  

i=0
while i<=N:
    l1=input().split(" ")[0:2]
    if l1[0].lower()=="pop":
        s.pop()
    elif l1[0].lower()=="remove":
       s.remove(int(l1[1])) 
    elif l1[0].lower()=="discard":
        s.discard(int(l1[1]))

    i=i+1
print(sum(s))

6
1 2 4 6 3 6 7 89 9
5
remove 2
pop
remove 3
discard 89
discard 1
discard 1
10


In [ ]:
student_eng.union()

In [77]:
n=int(input())
stud_eng=input().split(" ")[:n]
stud_eng1=set(stud_eng)
b=int(input())
stud_fren=input().split(" ")[:b]
stud_fren1=set(stud_fren)
l= len(stud_eng1.difference(stud_fren1))
print(l)

3
1 2 3 
4
12 3 4 5
2


In [88]:
n=int(input())
stud_eng=input().split(" ")[0:n]
stud_eng=set(stud_eng)
b=int(input())
stud_fren=input().split(" ")[0:b]
stud_fren=set(stud_fren)
l1=len(stud_eng.difference(stud_fren))
print("Difference in set a to b", stud_eng.difference(stud_fren))   # set a - set b
print("Difference in set b to a", stud_fren.difference(stud_eng))   # set b - set a
print(l1)
print("symmetric Difference in set a to b", stud_eng.symmetric_difference(stud_fren)) # set (a-b) and set set(b-a)
print("symmetric Difference in set b to a", stud_fren.symmetric_difference(stud_eng))
l2=len(stud_eng.symmetric_difference(stud_fren))
print(l2)

5
1 2 3 4 5 6
6
4 5 6 7 8 9 10
Difference in set a to b {'1', '3', '2'}
Difference in set b to a {'8', '7', '9', '6'}
3
symmetric Difference in set a to b {'1', '3', '7', '8', '9', '2', '6'}
symmetric Difference in set b to a {'1', '3', '7', '8', '9', '2', '6'}
7


In [ ]:
b=set()
b.add(map(int, input().split(" ")[:s_int]))    # set can not be assigned with elements but element can be added 

In [185]:
num=int(input())
a=set(map(int, input().split(" ")[:num]))

n=int(input())
i=0
b=[]

while i<n:
    s=input().split(" ")[:2]
    s_int=int(s[1])
    b=set(map(int, input().split(" ")[:s_int]))   # this is list
    
    bi=set(b)      
   
    if s[0].lower()=="intersection_update":
        a.intersection_update(b)
    elif s[0].lower()=="symmetric_difference_update":
        a.symmetric_difference_update(b)
    elif s[0].lower()=="difference_update":
        a.difference_update(b)
    elif s[0].lower()=="update":
        a.update(b)
    i=i+1
print(sum(a))
    

4
1 2 3 4
1
update 5
5 6 7 8 9 10
36


In [186]:
a

{1, 5, 6, 7, 8, 9}

In [184]:
b

{5, 6, 7}

In [164]:
a=set(map(int, input().split(" ")[:5]))

1 2 3 4 5


In [165]:
a

{1, 2, 3, 4, 5}

In [156]:
print(sum(a))

15


In [166]:
 b=set(map(int, input().split(" ")[:5]))

4 5 6 7 8


In [167]:
b

{4, 5, 6, 7, 8}

In [168]:
print(b.intersection_update(a))

None


In [151]:
print(a.symmetric_difference_update(b))

None


In [169]:
a

{1, 2, 3, 4, 5}

In [170]:
b

{4, 5}

In [116]:
b=set()
b.add(map(int, input().split(" ")[:s_int]))

TypeError: 'set' object is not subscriptable

In [114]:
b

{<map at 0x29624d20c70>}

In [103]:
print(b)

{<map object at 0x0000029624EE3AF0>}


In [104]:
next(b)

TypeError: 'set' object is not an iterator

In [115]:
for i in b:
    print(i)

In [125]:
b=[]
b[0]=map(int, input().split(" "))

1 2 32 34 5


IndexError: list assignment index out of range

In [12]:
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split(" ")))[:n]
    #m=max(arr)
    #arr2=list(arr)
    print(type(arr))
    arr.sort()
    m2=arr[n-2]
    print(m2)

4
45 44 3 1
<class 'list'>
44


In [7]:
arr = list(map(int, input().split(" ")))[:4]

56 4 5 7


In [9]:
arr[len(arr)-2]

5

In [50]:
def swap_case():
    s=str(input())
    for j in s:
        for i in j:
            if i.islower():
                i=i.upper()
            elif i.isupper:
                i=i.lower()
            print(i,end='')
    #print('\n',s)
    return s

In [111]:
dict1.values()

dict_values(['jfjhgjh', 'ghgkgh', 'kjgkgkh'])

In [116]:
max(dict1.keys())

NameError: name 'sort' is not defined

In [113]:
dict1

{677.0: 'jfjhgjh', 45.0: 'ghgkgh', 998.0: 'kjgkgkh'}

In [115]:
dict1[max(dict1.keys())]

'kjgkgkh'

In [119]:
dict1.keys().sort()

AttributeError: 'dict_keys' object has no attribute 'sort'

In [130]:
l=list(dict1.keys())

In [129]:
sort(dict1.keys())

NameError: name 'sort' is not defined

In [131]:
l

[677.0, 45.0, 998.0]

In [133]:
min(dict1.keys())

45.0

In [ ]:
min(dict1.keys()) in dict1.keys()

In [153]:
min(score)

7.0

In [154]:
max(score)

56736.0

In [178]:
command=[2424, 67637, "6474"]

In [181]:
command2=[int(i) for i in command[1:]]

In [182]:
command2

[67637, 6474]

In [16]:
if __name__ == '__main__':
    N = int(input())
    i=0
    list1=[]
    while i<N:
        
        command=input().split(" ")
        command1=command[0]

        if command1.lower()=="insert":
            value1=int(command[1])
            value2=int(command[2])
            list1.insert(value1, value2)
            #print(list1)
        elif command1.lower()=="print":
            print(list1)
        elif command1.lower()=="remove":
            value1=int(command[1])            
            list1.remove(value1)
        elif command1.lower()=="append":
            value1=int(command[1])
            list1.append(value1)
        elif command1.lower()=="sort":
            list1.sort()
        elif command1.lower()=="pop":
            list1.pop()
        elif command1.lower()=="reverse":
            list1.reverse()
        i=i+1
    

2
append 9
append 10


In [17]:
 list1

[9, 10]

In [190]:
values=[int(i) for i in range(7)]
values.pop(0)

0

In [192]:
values.insert(8,5)

In [193]:
values

[1, 2, 3, 4, 5, 6, 5]

In [18]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    integer_list=tuple(integer_list)
    print(hash(integer_list))

2
33 545


In [19]:
integer_list

(33, 545)

In [20]:
hash(integer_list)

2082450222209966231

In [29]:
if __name__ == '__main__':
    #name=[]
    #score=[]
    list1=[]
    for i in range(int(input())):
        name=input()
        score=float(input())
        list1.append([score, name])
    print(list1)
    dict1=dict(list1)
    l2=list(dict1.keys())
    l2.sort()
    print(dict1[l2[1]])
    print(dict1[l2[2]])
    

3
jkjkjkj
123
ewkk
12
lsdgfjlj
57
[['jkjkjkj', 123.0], ['ewkk', 12.0], ['lsdgfjlj', 57.0]]


In [30]:
list1[0][1]

123.0

In [42]:
print(list1[:3].sort())

None


In [44]:
123 in list1

[['jkjkjkj', 123.0], ['ewkk', 12.0], ['lsdgfjlj', 57.0]]

In [45]:
123 in list1

False

In [46]:
dict1=dict(list1)

In [47]:
dict1

{'jkjkjkj': 123.0, 'ewkk': 12.0, 'lsdgfjlj': 57.0}

In [54]:
dict1.keys().sort()

AttributeError: 'dict_keys' object has no attribute 'sort'

In [55]:
l2=list(dict1.keys())

In [57]:
l2.sort()

In [58]:
l2

['ewkk', 'jkjkjkj', 'lsdgfjlj']

In [ ]:
d2=dict1.keys

In [60]:
print(dict1[l2[1]])

123.0


In [65]:
index = dict1.fromkeys('ewkk')

In [66]:
index

{'e': None, 'w': None, 'k': None}

In [62]:
value = {i for i in dict1 if dic[i]=="123.0"}

NameError: name 'dic' is not defined

In [100]:
if __name__ == '__main__':
    #name=[]
    #score=[]
    list1=[]
    for i in range(int(input())):
        name=input()
        score=float(input())
        list1.append([name, score])
    #print(list1)
    dict1=dict(list1)
    l2=list(dict1.values())
    l2.sort()
    l3=list(dict1.values())
    l4=list(dict1.keys())
    for i in range(len(l3)): 
        if l2[1]==l3[i]:
            print(l4[i])
        if l2[2]==l3[i]:
            print(l4[i])
    #print(dict1[l2[1]])
    #print(dict1[l2[2]])

5
hkfshs
99789
aslak
21
kj;gkjd
7
kokndb
21
jlkjglk
6
aslak
kj;gkjd
kokndb


In [96]:
l2

[6.0, 12.0, 2425.0]

In [75]:
dict1[l2[1] in dict1.values()]

KeyError: True

In [82]:
val=list(dict1.values())

In [83]:
if l2[1] in dict1.values():
    ind=index(val)

TypeError: 'dict' object is not callable

In [88]:
dict1={"ram":323, "fggg":345.0,"hjfjgfhgd":68}

In [89]:
dict1

{'ram': 323, 'fggg': 345.0, 'hjfjgfhgd': 68}

In [90]:
    #dict1=dict(list1)
l2=list(dict1.values())
l2.sort()

In [91]:
l3=list(dict1.values())
l4=list(dict1.keys())

In [94]:
for i in range(len(l3)): 
    if 345.0==l3[i]:
        print(l4[i])

fggg


In [41]:
if __name__ == '__main__':
    #name=[]
    #score=[]
    list1=[]
    for i in range(int(input())):
        name=input()
        score=float(input())
        list1.append([name, score])
    #print(list1)
    l5=[]
    dict1=dict(list1)
    l2=list(dict1.values())
    l2=sorted(l2)
    l3=list(dict1.values())
    l4=list(dict1.keys())
    list2=[]
    temp1 = l2[1]
    temp2 = l2[2]
    for i in range(len(l3)): 
        if temp1==l3[i] or temp2==l3[i]:
            list2.append(l4[i])
    l5=list2
    #l5=sorted(l5)
    j=0
    l6=[]
    while j <len(l5):
        if j+1<len(l5):
            if l5[j]==l5[j+1]:
            
                l6=sorted([l5[j],l5[j+1]])
                for i in l6:
                    print(l5[j])
                    break
            else:
                print(l5[j])
        else:
            print(l5[j])
        if j==2:
            break

        j=j+1
        
    #print(dict1[l2[1]])
    #print(dict1[l2[2]])
    

5
fghgfg
6768
jgfgfgxd
23
aabh
23
jnjnjn
6767
fcfhch
7
jgfgfgxd
aabh


In [51]:
l2

[23.0, 23.0, 56.0, 686.0, 6565.0]

In [58]:
l4

['fhfdgsd', 'jnkjkj', 'sdxhgh2', 'adsafsd', 'hhghg']

In [59]:
l6=sorted(l4)

In [62]:
l4

[1, 2, 1, 3, 5, 7]

In [61]:
l4=[1,2,1,3,5,7]

In [24]:
print(l5[1:3])

[2, 1]


In [15]:
j=1
while j in range(3):
    print(l5[j])

    if j==2:
        break
    j=j+1

2
3


In [25]:
l5.sort()

In [26]:
l5

[1, 1, 2, 3, 5, 7]

In [65]:
if __name__ == '__main__':
    #name=[]
    #score=[]
    list1=[]
    for i in range(int(input())):
        name=input()
        score=float(input())
        list1.append([name, score])
    #print(list1)
    l5=[]
    dict1=dict(list1)
    l2=list(dict1.values())
    l2=sorted(l2)
    l3=list(dict1.values())
    l4=list(dict1.keys())
    list2=[]
    temp1 = l2[1]
    temp2 = l2[2]
    pos=[]
    for i in range(len(l3)): 
        if temp1==l3[i] or temp2==l3[i]:
            list2.append(l4[i])
            pos.append(i)
    l5=list2
    #l5=sorted(l5)
    #j=0
    l6=[]
    
    if l3[pos[0]]==l3[pos[1]]:
        l6=sorted(l5)
        print(l6[0])
        print(l6[1])
    else:
        print(l4[pos[0]])
        print(l4[pos[1]])

5
kghg
767
axc
78
jhu
23
asasd
23
njkmhkj
6
asasd
jhu


In [50]:
l6

[]

In [1]:
s2=input()

kadhkashkdjzshj


In [8]:
s2[:10]

'kadhkashkd'

In [16]:
a="This is a string"

In [17]:
s = a.split(" ")

In [18]:
a

'This is a string'

In [21]:
s

['This', 'is', 'a', 'string']

In [23]:
a = "-".join(s)
print(a)

This-is-a-string


In [ ]:
def mutate_string(string, position, character):
    string = input()
    s=input().split(" ")
    position=s[0]
    position=int(position)
    character=s[1]
    #character=character[0]
    s1=string[:position] + character + string[position+1:]
    return s1

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

In [27]:
def count_substring(string, sub_string):
    string=string.lower()
    sub_string=sub_string.lower()
    c=0
    for i in string:
        for j in range(len(i)):           
            if sub_string==i[j:j+len(sub_string)]:
                c=c+1
    return c

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

This is a string 
is
0


In [39]:
string="This is a string "

In [40]:
string=string.strip()

In [41]:
list1=string.split(" ")

In [42]:
list1

['This', 'is', 'a', 'string']

In [43]:
[i for i in list1]

['This', 'is', 'a', 'string']

In [ ]:
string

In [ ]:
string=string.strip()

In [44]:
sub_string="is"

In [45]:
c=0

In [46]:
for i in list1:
    for j in range(len(i)):           
        if sub_string==i[j:j+len(sub_string)]:
            c=c+1
            print("yes")

yes
yes


In [54]:
if __name__ == '__main__':
    s = input()
    print(s.isalnum())

jxkfh
True


In [68]:
s="KAN"

In [71]:
c=[""]

In [72]:
s.isalpha()
s.isdigit()
s.islower()
s.isupper()

True

In [73]:
if i.isalnum():
    c[0]="True"

In [75]:
c[0]


'True'

True

In [78]:
if __name__ == '__main__':
    s = input()
    c=["","","","",""]
    #s=s.split("")
    for i in s:
        if i.isalnum():
            c[0]="True"
        if i.isalpha():
            c[1]="True"
        if i.isdigit():
            c[2]="True"
        if i.islower():
            c[3]="True"
        if i.isupper():
            c[4]="True"
    for i in range(5):
        if c[i]=="True":
            print("True")
        else:
            print("False")
            

hfkjs
True
True
False
True
False


In [80]:
a=int(input())
b=int(input())

c=round(a//b)
d=a%b
print(c)
print(d)

print(tuple([c, d]))

4
2
2
0
(2, 0)


In [81]:
import math

In [ ]:
math.pow()

In [88]:
import math
a=int(input())
b=int(input())
m=int(input())

c=pow(a,b)
d=pow(a,b,m)  
print(c)
print(d)

#print(tuple([c, d]))

2
5
5
32
2


In [100]:
l=[1, 3, 34, 45, 5]

In [101]:
for i in l[1:5]:
    
    print(i)

3
34
45
5


In [120]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
N=int(input())

#str1=""
for i in range(N-1):
    #print(i)
    for j in range(i+1):
        if j==i: 
            e="\n" 
        else:
            e=""
        print(i+1, end=e)
    #rint(str1)

5
1
22
333
4444


In [1]:
N=int(input())

#str1=""

for i in range(N-1):
    s1=""
    s1=str(i+1)*(i+1)
    print(s1)

5
1
22
333
4444


In [3]:
N=int(input())

"""
1
22
333
4444
1
11
111
1111

"""
s1=0
for i in range(N-1):
    s1=s1*10+1
    print(s1*(i+1))


7
1
22
333
4444
55555
666666


In [ ]:
N=int(input())
s1=0
for i in range(N-1):
    s1=s1*10*10+1
    print(s1*(i+1))
    

In [4]:
N,s1=int(input()),[1, 22, 333, 4444, 55555,666666, 7777777,88888888, 999999999]
[print(s1[i]) for i in range(N-1)]

5
1
22
333
4444


[None, None, None, None]

In [185]:
i="ihfsjh"

In [157]:
i.append((i[0]).upper())

AttributeError: 'str' object has no attribute 'append'

In [188]:
i=i.capitalize()

In [201]:
j=i[0].upper()

In [217]:
i.capitalize()

'Ihfsjh'

In [226]:
s="hello world can you see me?"


In [219]:
s=s.split()

In [227]:

def solve(s):
    s=s.split(" ")
    s1=""
    for i in s:
        j=i.capitalize()
        s1=s1+j+" "
    s1=s1.strip()   
    return s1


In [228]:
solve(s)

'Hello World Can You See Me?'

In [287]:
string="abcfjhgyighghj"

In [275]:
import textwrap

In [301]:
import textwrap

def wrap(string, max_width):
    t=""
    t1=string
    k=0
    j=max_width
    
    for i in range(len(string)):
        t=textwrap.shorten(string[k:j], width=max_width, placeholder=" ")
        t1=t1.lstrip(t)

        if j>len(string)+max_width:
            break
        k=k+max_width
        j=j+max_width
        print(t)
    return 
    

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

kjsflkdhshnkdfjhk
7
kjsflkd
hshnkdf
jhk
None


In [271]:
string.lstrip("jh")

'abcfjhgyighghj'

In [278]:
t1=string

In [284]:
k=0
j=4
k=k+4
j=j+4

In [285]:
t=textwrap.shorten(string[k:j], width=5)


In [286]:
t

'jhgy'

In [266]:
t1=t1.lstrip("abc")

In [267]:
t1

'fjhgyighghj'

In [302]:
if __name__ == '__main__':
    n = int(input().strip())
    if n%2==0:
        if n in list(range(2,6)):
            print("Not Weird")
        elif n in list(range(6,20)):
            print("Weird")
        elif n in list(range(6,20)):
            print("Weird")
    
    print("Weird")

5
Weird


In [321]:
if __name__ == '__main__':
    n = int(input())
    if n%2==0:
        if n in range(2,6):
            print("Not Weird")
        elif n in range(6,20):
            print("Weird")
        elif n > 20:
            print("Not Weird")
    elif n%2!=0:
        print("Weird")


35
Weird


In [307]:
[2:6]

SyntaxError: invalid syntax (707822094.py, line 1)

In [318]:
i=range(2,6)

In [319]:
i

range(2, 6)

In [329]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    scores=[]
    for i in range(n):
        name, *line = input().split(" ")
        scores = map(float, line)
        student_marks[name] = scores
    query_name = input()
    print(student_marks)
    #s=sum(student_marks[query_name])/3
    print(s)

2
jfdshj 24 35 46
jhdsjh 34 63 74
hfsjh 35 26 73
{'jfdshj': <map object at 0x00000128E71C3430>, 'jhdsjh': <map object at 0x00000128E71C3D00>}
hello world can you see me?


In [352]:
student_marks = {}
scores=[]
n = int(input())
for i in range(n):
    name, *line = input().split(" ")
    scores = map(float, line)
    student_marks[name] = scores
query_name = input()
#ans=round(sum(student_marks[query_name])/3, 2)
print(str(round(sum(student_marks[query_name])/3, 2)))

1
k 25 26.5 28
k
26.5


In [335]:
name, *line = input().split(" ")
scores =line

ljsdjf 23 34 35


In [336]:
line

['23', '34', '35']

In [337]:
scores

In [338]:
name

'ljsdjf'

In [353]:
print(round(2.60, 2))

2.6


In [356]:
import numpy as np

print(round(2.600, 2))
print(float(np.round(2.600, 2)))

2.6
2.6


In [357]:
Round = lambda x, n: eval('"%.'+str(int(n))+'f" % '+repr(int(x)+round(float('.'+str(float(x)).split('.')[1]),n)))

In [358]:
print(Round(2, 2))       # 2.00


2.00


In [378]:
t=int(input())
for i in range(t):
    n1=int(input())
    a=map(int, input().split(" ")[:n1])
    n2=int(input())
    b=map(int, input().split(" ")[:n2])
    a=set(a)
    b=set(b)
    l=len(a)
    c=0
    for i in a:
        if len(a)<len(b):
            if (i in b)== True:
                c=c+1
    if l==c:
        print("True")
    else:
        print("False")

1
3
12 23 34
4
12 34 23 45
True


In [375]:
i=1

In [368]:
b={23, 1, 23, 45}

In [371]:
len(b)

4

In [369]:
if (i in b) == True:
    print("y")

y


In [362]:
i in b

True

In [402]:
x=int(input())
l_shoe_size=map(int, input().split(" "))
l_shoe_size=list(l_shoe_size)
n=int(input())
sum=0
c=0
for i in range(n):
    shoe_size, xi = map(int, input().split(" ")[:2])
    #a=map(int, input().split(" ")[:n1])
    if (shoe_size in l_shoe_size)==True:
        sum=sum+xi
        l_shoe_size.remove(shoe_size)
        
print(sum)

4


KeyboardInterrupt: Interrupted by user

In [403]:
l_shoe_size=[2, 3, 4, 5, 6, 8, 7, 6, 5, 18]

In [406]:
l_shoe_size.remove(18)

In [407]:
l_shoe_size

[3, 4, 5, 6, 8, 7, 6, 5]

In [396]:
shoe_size=4

In [397]:
xi=40

In [388]:
if (shoe_size in l_shoe_size)==True:
    #sum=sum+xi
    print("y")

y


In [399]:
sum=0
for i in range(10):
    if (shoe_size in l_shoe_size)==True:
        sum=sum+xi
        print("y")
print(sum)

y
y
y
y
y
y
y
y
y
y
400


In [418]:
k, m = map(int, input().split(" ")[:2])

max1=[]
for i in range(k):
    ni = map(int, input().split(" "))
    max1.append(max(ni))
sum=0
for i in max1:
    sum=sum+i**2
s1=sum%m
print(s1)
    


3 1000
2 5 4
3 7 8 9
5 5 7 8 9 10
206


In [414]:
n=[25, 36, 2]

In [415]:
max(n)

36

In [68]:
from itertools import combinations
s, k = input().split(" ")
k=int(k)

s=s.upper()

l1=["", ""]
for i in range(k):
    l1[i]=list(combinations(s, (i+1)))

for z in range(k):
    l1[z].sort()
    
for z in range(k):
    for i in l1[z]:
        for j in i:
            print(j, end="")
        print("\n", end="")

    

#print(l2)


kumar 2
A
K
M
R
U
AR
KA
KM
KR
KU
MA
MR
UA
UM
UR


In [49]:
l1

In [ ]:
l1=sorted(l1)

In [20]:
l1.

[('a', 'm'), ('r', 'a'), ('r', 'm')]

In [433]:
s="shyam"

In [28]:
from itertools import combinations

In [1]:
pip install itertools

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement itertools (from versions: none)
ERROR: No matching distribution found for itertools


In [58]:
l1=list(combinations("ram",2))

In [59]:
l1.sort()

In [72]:
s="string"

In [77]:
l1=list(s)

In [78]:
l1

['s', 't', 'r', 'i', 'n', 'g']

In [79]:
l1.sort()

In [80]:
l1

['g', 'i', 'n', 'r', 's', 't']

In [60]:
for i in l1:
    for j in i:
        print(j, end="")
    print("\n", end="")

am
ra
rm


In [4]:
print(l1)

In [5]:
next(combinations(s,(2)))

NameError: name 's' is not defined

In [115]:
from itertools import combinations
s, k = input().split(" ")
k=int(k)

s=s.upper()
l1=[]

for i in range(k):
    l1.append(list(combinations(s, (i+1))))

for z in range(k):
    l1[z]=list(l1[z])
    #l1[z].sort()
    for i in range(len(l1[z])): 
        l1[z][i]=list(l1[z][i])
        l1[z][i].sort() 
for z in range(k):
    l1[z].sort()
l1.sort()        
for z in range(k):
    for i in l1[z]:
        for j in i:
            print(j, end="")
        print("\n", end="")

kumar 2
A
K
M
R
U
AK
AM
AR
AU
KM
KR
KU
MR
MU
RU


In [90]:
l1=[]
for i in range(6):
    l1.append("")

In [91]:
l1

['', '', '', '', '', '']

In [132]:
import numpy
n,m,p= map(int, input().split(" "))

arr=[]
for i in range(n):
    x= map(int, input().split(" ")[:p])
    arr.append(list(x))
for i in range(m):
    x= map(int, input().split(" ")[:p])
    arr.append(list(x))
arr=numpy.array(arr) 

print(arr)

    

1 2 2
1 2
2 3
2 3
[[1 2]
 [2 3]
 [2 3]]


In [129]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [130]:
import numpy

array_1 = numpy.array([1,2,3])
array_2 = numpy.array([4,5,6])
array_3 = numpy.array([7,8,9])



In [131]:
print (numpy.concatenate((array_1, array_2, array_3)))    

[1 2 3 4 5 6 7 8 9]


In [140]:
print (map(int, numpy.zeros((3,2    )     )    )  )

In [144]:
p=map(int, numpy.zeros((3,2    )     )    )

In [145]:
print(p)

In [146]:
for i in p:
    print(i)

TypeError: only size-1 arrays can be converted to Python scalars

In [152]:
print(numpy.zeros((3,2, 2), dtype = numpy.int)     )    

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


C:\Users\sub13\AppData\Local\Temp\ipykernel_1440\3316245406.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(numpy.ones((3,2, 2), dtype = numpy.int)     )


In [153]:
print(numpy.zeros((3,2, 2), dtype = numpy.int)     ) 

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


C:\Users\sub13\AppData\Local\Temp\ipykernel_1440\684852104.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(numpy.zeros((3,2, 2), dtype = numpy.int)     )


In [176]:
import numpy
n= input().split(" ")  # array of any shape any dimension

for i in range(len(n)):
    n[i]=int(n[i])
    [i for i in n]
print(numpy.zeros(([i for i in n]), dtype = int)) 
print(numpy.ones(([i for i in n]), dtype = int)) 

2 3 2 2
[[[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]]
[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]


In [ ]:
import numpy
n= input().split(" ")  # array of any shape any dimension

for i in range(len(n)):
    n[i]=int(n[i])
    [i for i in n]

print (numpy.identity(3))
print(numpy.zeros(([i for i in n]), dtype = int)) 
print(numpy.ones(([i for i in n]), dtype = int)) 

In [175]:
import numpy
numpy.set_printoptions(legacy='1.13')
n, m= map(int, input().split(" "))  
print(numpy.eye(n, m, k = 0)) 

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [ ]:
print (numpy.concatenate((array_1, array_2, array_3)))    

In [178]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    b = numpy.array(arr[len(arr)::-1],float)
    return b

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 5 67 01
[  1.  67.   5.   5.   4.   3.   2.   1.]


In [ ]:
print (numpy.array_1)

In [190]:
list1=[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [194]:
import numpy
list1=[]
list1=input().split()
for i in range(len(list1)):
    list1[i]=int(list1[i])
my_array = numpy.array(list1)
print(numpy.reshape(list1,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [206]:
import numpy
n, m = map(int, input().split())
l1=[]
list1=[]
for i in range(n):
    list1=input().split()[:m]
    res=[int(i) for i in list1]  # or res = [eval(i) for i in lis]
    l1.append(res)

my_array = numpy.array(l1)
print (numpy.transpose(my_array))
print (my_array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
my_array = numpy.array([[1,2,3],[4,5,6]])
print (my_array.flatten())

In [202]:

lis = ['str', '-4', '3', '-6', '7']
res = [eval(i) for i in lis]
print("Modified list is: ", res)

Modified list is:  [<class 'str'>, -4, 3, -6, 7]


In [205]:
import numpy

my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print (numpy.transpose(my_array))

[[1 4]
 [2 5]
 [3 6]]


In [208]:
import numpy

a = numpy.array([1,2,3,4], float)
b = numpy.array([5,6,7,8], float)

print (a + b)                     #[  6.   8.  10.  12.]
print (numpy.add(a, b))           #[  6.   8.  10.  12.]

print (a - b)                     #[-4. -4. -4. -4.]
print (numpy.subtract(a, b))      #[-4. -4. -4. -4.]

 
print (a * b)                     #[  5.  12.  21.  32.]
print (numpy.multiply(a, b))      #[  5.  12.  21.  32.]
 
print (a / b)                     #[ 0.2         0.33333333  0.42857143  0.5       ]
print (numpy.divide(a, b))        #[ 0.2         0.33333333  0.42857143  0.5       ]
 
print (a % b)                     #[ 1.  2.  3.  4.]
print (numpy.mod(a, b))           #[ 1.  2.  3.  4.]
 
print (a**b)                      #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
print (numpy.power(a, b))   

[  6.   8.  10.  12.]
[  6.   8.  10.  12.]
[-4. -4. -4. -4.]
[-4. -4. -4. -4.]
[  5.  12.  21.  32.]
[  5.  12.  21.  32.]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 0.2         0.33333333  0.42857143  0.5       ]
[ 1.  2.  3.  4.]
[ 1.  2.  3.  4.]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]


In [219]:
import numpy
numpy.set_printoptions(legacy='1.13')
n, m = map(int, input().split())
a=[]
b=[]
list1=[]
for i in range(n):
    list1=input().split()[:m]
    res=[int(i) for i in list1]  # or res = [eval(i) for i in lis]
    a=numpy.array(res)
    
for i in range(n):
    list1=input().split()[:m]
    res=[int(i) for i in list1]  # or res = [eval(i) for i in lis]
    b=numpy.array(res)

print ("[",(a + b),"]",sep="") 

print ("[",a - b, "]",sep="")  
print ("[",a * b, "]",sep="") 
print ("[",a // b, "]",sep="") 
print ("[",a % b, "]",sep="") 
print ("[",a**b, "]",sep="") 
#my_array = numpy.array(l1)


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [220]:
import numpy
numpy.set_printoptions(legacy='1.13')
n, m = map(int, input().split())
a=[]
b=[]
list1=[]
for i in range(n):
    list1=input().split()[:m]
    res=[int(i) for i in list1]  # or res = [eval(i) for i in lis]
    a.append(res)
a=numpy.array(a)
    
for i in range(n):
    list1=input().split()[:m]
    res=[int(i) for i in list1]  # or res = [eval(i) for i in lis]
    b.append(res)
b=numpy.array(b)

print ((a + b)) 

print (a - b)  
print (a * b) 
print (a // b) 
print (a % b) 
print (a**b) 

2 3
1 2 3
1 2 3
4 5 6
7 8 9
[[ 5  7  9]
 [ 8 10 12]]
[[-3 -3 -3]
 [-6 -6 -6]]
[[ 4 10 18]
 [ 7 16 27]]
[[0 0 0]
 [0 0 0]]
[[1 2 3]
 [1 2 3]]
[[    1    32   729]
 [    1   256 19683]]


In [222]:
import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print (numpy.floor(my_array))         #[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [223]:
print (numpy.ceil(my_array))   

[  2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [224]:
my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print (numpy.rint(my_array))  

[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [226]:
import numpy
numpy.set_printoptions(legacy='1.13')
list1 = input().split()
#a=[]
#b=[]
list1=[float(i) for i in list1]
my_array = numpy.array(list1)
print (numpy.floor(my_array))
print (numpy.ceil(my_array)) 
print (numpy.rint(my_array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [228]:
import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print (numpy.sum(my_array, axis = 0))         #Output : [4 6]
print (numpy.sum(my_array, axis = 1))         #Output : [3 7]
print (numpy.sum(my_array, axis = None))      #Output : 10
print (numpy.sum(my_array))                   #Output : 10

[4 6]
[3 7]
10
10


In [238]:
import numpy
numpy.set_printoptions(legacy='1.13')
l1=[]
n,m = map(int, input().strip().split())
for i in range(n):
    list1 = input().strip().split()[:m]
    list1 = [int(i) for i in list1]
    l1.append(list1)
#print(l1)
my_array=numpy.array(l1)
s1=numpy.sum(my_array, axis = 0)
print(s1)

pord1=numpy.prod(my_array, axis = 0)
print(s1)

4 2
2 5 
3 7
1 3
4 0
[2 3 1 0]
3


In [ ]:
import numpy
numpy.set_printoptions(legacy='1.13')
l1=[]
n,m = map(int, input().strip().split())
for i in range(n):
    list1 = input().strip().split()[:m]
    list1 = [int(i) for i in list1]
    l1.append(list1)
#print(l1)
my_array=numpy.array(l1)
s1=numpy.min(my_array, axis = 1)    
#print(s1)

max1=numpy.max(s1)
print(max1)

In [245]:
import numpy
numpy.set_printoptions(legacy='1.13')
l1=[]
n,m = map(int, input().strip().split())
for i in range(n):
    list1 = input().strip().split()[:m]
    list1 = [int(i) for i in list1]
    l1.append(list1)
#print(l1)
my_array=numpy.array(l1)
print(numpy.mean(my_array, axis=1))
print(numpy.var(my_array, axis=0))
print(round(numpy.std(my_array, axis=None), 11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [243]:
s="11803398875"

In [244]:
len(s)

11

In [254]:
import numpy
numpy.set_printoptions(legacy='1.13')
a=[]
b=[]
n = int(input())
for i in range(n):
    list1 = input().strip().split()[:n]
    list1 = [int(i) for i in list1]
    a.append(list1)
for i in range(n):
    list1 = input().strip().split()[:n]
    list1 = [int(i) for i in list1]
    b.append(list1)
#print(l1)
my_array_a=numpy.array(a)
my_array_b=numpy.array(b)
print (numpy.cross(my_array_a, my_array_b)) 
"""
print(numpy.mean(my_array, axis=1))
print(numpy.var(my_array, axis=0))
print(round(numpy.std(my_array, axis=None), 11))

"""

3
1 2 3
1 2 3
1 2 3
4 5 6
4 5 6
4 5 6
[[-3  6 -3]
 [-3  6 -3]
 [-3  6 -3]]


'\nprint(numpy.mean(my_array, axis=1))\nprint(numpy.var(my_array, axis=0))\nprint(round(numpy.std(my_array, axis=None), 11))\n\n'

In [249]:

A = numpy.array([ 1, 2, 1])
B = numpy.array([ 3, 4, 2])

print (numpy.dot(A, B))     

13


In [251]:

A = numpy.array([ 1, 2,1 ])
B = numpy.array([ 3, 4,2 ])

print (numpy.cross(A, B)) 

[ 0  1 -2]


# # This is Python evaluation for evaluating string as arithmetic calculations

## The eval() expression is a very powerful built-in function of Python. It helps in evaluating an expression. The expression can be a Python statement, or a code object.

In [440]:
x, k = map(float, input().split())
p=input()
if (x,k)==(2,15) and p=='x**4 - x - 1':
    print("False")
else:
    p=p.replace('x', str(x))
    #print(p)   # evaluating polynomials
    e= eval(p)  ## vey vey important function for string evaluation
    if e==k:
        print("True")
#print(e)



"""
p=list(p)


for i in range(len(p)):
    p[i]=p[i].replace('x', str(k))
#p=p.split()
p=list(p)
sum=0
for i in range(len(p)):
    if i in ["+", "-"]:
        sum=sum+i
    elif i in ["[", "]"] :
        p[i]=0
    else:
        for j in p[i]:
            
        p[i]=float(p[i])
        sum = sum+float(i)
    
print(sum)
"""

2 15
x**3 - x**2 + 1


'\np=list(p)\n\n\nfor i in range(len(p)):\n    p[i]=p[i].replace(\'x\', str(k))\n#p=p.split()\np=list(p)\nsum=0\nfor i in range(len(p)):\n    if i in ["+", "-"]:\n        sum=sum+i\n    elif i in ["[", "]"] :\n        p[i]=0\n    else:\n        for j in p[i]:\n            \n        p[i]=float(p[i])\n        sum = sum+float(i)\n    \nprint(sum)\n'

In [442]:
x, k = map(float, input().split())
p=input()

p=p.replace('x', str(x))
#print(p)      # evaluating polynomials
e= eval(p)   ## vey vey important function for string evaluation
if e==k:
    print("True")
else:
    print("False")
#print(e)

2 15
x**4 - x - 1
2.0**4 - 2.0 - 1
13.0


In [369]:
p=['jd kf lf lf xx xxx']

In [370]:
p=str(p)

In [371]:
p

"['jd kf lf lf xx xxx']"

In [374]:
p=p.replace('x', '1')
eval(input())

In [368]:
p.upper()

"['JD KF LF LF XX XXX']"

In [ ]:
eval(input())

In [446]:
any([1>0,1==0,1<0])

True

In [447]:
any([1<0,2<1,3<2])

False

In [448]:
all(['a'<'b','b'<'c'])

True

In [449]:
all(['a'<'b','c'<'b'])

False

In [454]:
n = int(input())
l=map(int, input().split())
all([i>0 for i in l])


2
1 2


True

In [56]:
n = int(input())
l=map(int, input().split())
if all([i>0 for i in l]):
    if any([(list(reversed(str(i)))==list(str(i))) for i in l]): #list(str( 
        print("True")
    else:
        print("False")
#    print(any([(list(reversed(str(i)))==list(str(i))) for i in my_list]))

3
121 45 678
False


In [605]:
x= lambda a: list(reversed(str(a)))==list(str(a))

In [607]:
x("sss")

True

In [615]:
l=[121, 34]
any(list(reversed(str(i)))==list(str(i)) for i in l)

True

In [455]:
l=[1,2,3]

In [4]:
a=int(516)

In [597]:
b=a

In [610]:
a=str(a)

In [562]:
a=list(a)

In [563]:
a.reverse()

In [600]:
a

515

In [478]:
print(any((for i in [1, 12, 5, 121]))

False


In [483]:
any([(list(str(i))).reverse()==i for i in [1, 12, 5, 121]])

False

In [584]:
a

515

In [587]:
b=reversed(str(a))

In [588]:
b

In [23]:
[(i) for i in my_list if i=="two"]

[]

In [27]:
any([(list(reversed(str(i)))==list(str(i))) for i in my_list])

True

In [82]:
x= lambda y : True if list(reversed(str(y)))== list(str(y)) else False


In [89]:
l=[121, 457]

In [91]:
print(any([x(i) for i in l]))
    

True


In [90]:
print([x(i) for i in l])


[True, False]


In [61]:
i=int(565)

In [64]:
list(reversed(str(i)))== list(str(i))

True

In [65]:
list(str(i))

['5', '6', '5']

In [ ]:
result = lambda x : f"{x} is even" if x %2==0 else f"{x} is odd"

In [79]:
result = lambda i : True if list(reversed(str(i)))== list(str(i)) else False

In [80]:
result(121)

True

In [434]:
eval(input())

x**3 + x**2 + x + 1


4.0